# Generated by Django 3.2.8 on 2021-11-01 01:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrator',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='main_role',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='surname',
        ),
        migrations.AddField(
            model_name='administrator',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
