# Generated by Django 3.2.7 on 2021-11-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211031_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
