# Generated by Django 3.2.8 on 2021-11-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='surname',
            new_name='last_name',
        ),
    ]
