# Generated by Django 3.2.8 on 2021-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20211031_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1),
        ),
    ]
