# Generated by Django 3.2.8 on 2021-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
