# Generated by Django 3.2.8 on 2021-11-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='name_admin',
            new_name='name',
        ),
    ]
