# Generated by Django 3.2.8 on 2021-11-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0002_auto_20211101_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='date',
            new_name='date_created',
        ),
    ]
