# Generated by Django 3.2.8 on 2021-11-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211031_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='id_category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name_subcategory',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='image',
            new_name='photo',
        ),
    ]
