# Generated by Django 3.2.8 on 2021-11-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211031_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_providor',
            new_name='id_provider',
        ),
    ]
