# Generated by Django 3.2.7 on 2021-11-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211101_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_provider',
            new_name='id_supplier',
        ),
    ]
