# Generated by Django 3.2.7 on 2021-11-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20211105_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_on',
        ),
    ]
